# Generated by Django 3.1.6 on 2021-02-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('written_by', models.CharField(max_length=200)),
                ('edited_by', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Writter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_editor', models.BooleanField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
